[package]
name = "circuit-simulator"
version = "0.1.0"
authors = ["kazukiyoshida"]
edition = "2018"

[lib]
path = "src/lib.rs"
name = "circuit_simulator"

[dependencies.avr-emulator]
path = "../avr-emulator"

[dependencies]
wasm-bindgen = "0.2"
nalgebra = "0.19.0"
