[package]
name = "circuit-simulator-wasm"
version = "0.1.0"
authors = ["kazukiyoshida"]
edition = "2018"

[lib]
path = "src/lib.rs"
name = "circuit_simulator_wasm"
crate-type = ["cdylib"]

[dependencies.circuit-simulator]
path = "../"

[dependencies]
wasm-bindgen = "0.2"
